name: Release Unity Package

on:
    push:
        tags:
            - 'v*'

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
    export-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Extract changelog for this version
              id: changelog
              run: |
                VERSION=${GITHUB_REF##*/}  # e.g. "v1.0.0"
                sed -n "/^## \[${VERSION}\]/,/^## \[/p" CHANGELOG.md | sed '$s/^## \[.*//; /^$/d' > current_changelog.md

            - name: Cache Library
              uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                  restore-keys: Library-

            - name: Unity - Builder
              uses: game-ci/unity-builder@v4
              env:
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  buildMethod: UnityBuilderAction.ExportPackage.Export
                  projectPath: EepyDemoProject

            - name: Upload to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: EepyDemoProject/Build/Eepy.unitypackage
                  body_path: extracted_changelog.md
