name: Release Unity Package

on:
    push:
        tags:
            - 'v*'

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
    export-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Cache Library
              uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                  restore-keys: Library-

            - name: Export Unity Package
              uses: game-ci/unity-builder@v4
              with:
                  targetPlatform: StandaloneWindows64
                  projectPath: ExampleProject
                  customParameters: '-batchmode -executeMethod ExportPackage.PerformExport'
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

            - name: Upload to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: Build/ExampleProject.unitypackage
