name: Release Unity Package

on:
    push:
        tags:
            - 'v*'

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
    export-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Cache Library
              uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                  restore-keys: Library-

            - name: Setup Unity
              uses: game-ci/unity-activate@v2

            - name: Export Unity Package
              run: |
                  unity-editor \
                  -batchmode \
                  -quit \
                  -projectPath ExampleProject \
                  -executeMethod ExportPackage.PerformExport \
                  -logFile /dev/stdout

            - name: Upload to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: Build/ExampleProject.unitypackage
