name: Sync Unity Folders to Main

on:
    push:
        branches:
            - dev
        paths:
            - '.github/workflows/sync-library-files.yml'
            - 'ExampleProject/Assets/Scripts/**'
            - 'ExampleProject/Assets/Resources/**'
            - 'ExampleProject/Assets/Editor/Utils/**'

jobs:
    sync-folders:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout dev branch
              uses: actions/checkout@v4
              with:
                  ref: dev
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: Configure Git
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Switch to main branch
              run: |
                  git checkout main
                  git pull origin main

            - name: Copy Unity folders from dev
              run: |
                  # Remove existing folders in root if they exist
                  sudo rm -rf Assets/

                  # Copy folders from ExampleProject to root
                  git checkout dev -- ExampleProject/Assets/Scripts/Utils/
                  git checkout dev -- ExampleProject/Assets/Resources/
                  git checkout dev -- ExampleProject/Assets/Editor/Utils/

                  # Create destination directories
                  mkdir -p Assets/Scripts/
                  mkdir -p Assets/Editor/

                  # Move the folders to root, excluding .meta files
                  if [ -d "ExampleProject/Assets/Scripts/Utils" ]; then
                    find ExampleProject/Assets/Scripts/Utils/ -type f ! -name "*.meta" -exec mv {} Assets/Scripts/ \;
                  fi

                  if [ -d "ExampleProject/Assets/Resources" ]; then
                    find ExampleProject/Assets/Resources/ -type f ! -name "*.meta" -exec mv {} Assets/Resources/ \;
                  fi

                  if [ -d "ExampleProject/Assets/Editor/Utils" ]; then
                    find ExampleProject/Assets/Editor/Utils/ -type f ! -name "*.meta" -exec mv {} Assets/Editor/ \;
                  fi

            - name: Add all files
              run: |
                  git add .

            - name: Check for changes
              id: check_changes
              run: |
                  if [ -n "$(git status --porcelain)" ]; then
                    echo "changes=true" >> $GITHUB_OUTPUT
                  else
                    echo "changes=false" >> $GITHUB_OUTPUT
                  fi

            - name: Commit and push changes
              if: steps.check_changes.outputs.changes == 'true'
              run: |
                  git commit -m "bot-chore: sync library files from dev"
                  git push origin main

            - name: No changes detected
              if: steps.check_changes.outputs.changes == 'false'
              run: echo "No changes to sync from dev branch"
